In [1]:
import torch
a = torch.zeros(2, 3)
b = torch.ones(2, 3)
c = torch.randn(2, 3)
print(a)
print(b)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.6196, -1.4761, -0.8153],
        [-1.1934,  1.2537,  2.6364]])


In [3]:
# 从 numpy 数组创建张量
import numpy as np
numpy_array = np.array([[1,2,3],[4,5,6]])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [5]:
# 在指定设备 CPU或GPU上创建张量
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
d = torch.randn(2, 3, device=device)
print(d)

tensor([[-0.2999, -0.2912,  1.1246],
        [-0.3504, -1.1622,  0.0888]])


In [7]:
print(a+b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
print(a*b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
g = torch.randn(2,3)
g

tensor([[ 0.2259, -0.9172, -0.3760],
        [ 1.0871, -0.4150,  0.3021]])

In [13]:
g.t()

tensor([[ 0.2259,  1.0871],
        [-0.9172, -0.4150],
        [-0.3760,  0.3021]])

In [17]:
g.shape

torch.Size([2, 3])

PyTorch的张量支持自动微分，这是深度学习中的关键特性。当你创建一个需要梯度的张量时，PyTorch可以自动计算其梯度：

In [25]:
# 创建一个需要梯度的张量
tensor_requires_grad = torch.tensor([1.0], requires_grad=True)

tensor_result = tensor_requires_grad * 2
tensor_result.backward()
print(tensor_requires_grad.grad)

tensor([2.])


自动求导（Automatic Differentiation，简称Autograd）是深度学习框架中的一个核心特性，它允许计算机自动计算数学函数的导数。

在深度学习中，自动求导主要用于两个方面：一是在训练神经网络时计算梯度，二是进行反向传播算法的实现。

自动求导基于链式法则（Chain Rule），这是一个用于计算复杂函数导数的数学法则。链式法则表明，复合函数的导数是其各个组成部分导数的乘积。在深度学习中，模型通常是由许多层组成的复杂函数，自动求导能够高效地计算这些层的梯度。

In [28]:
x = torch.randn(2, 2, requires_grad=True)
x

tensor([[-1.9450,  0.0844],
        [-0.4263, -1.4382]], requires_grad=True)

In [30]:
y = x + 2
z = y * y * 3
out=z.mean()
print(out)

tensor(5.3547, grad_fn=<MeanBackward0>)


In [32]:
out.backward()
x.grad

tensor([[0.0825, 3.1265],
        [2.3605, 0.8428]])

神经网络是一种模仿人脑神经元连接的计算模型，由多层节点（神经元）组成，用于学习数据之间的复杂模式和关系。

神经网络通过调整神经元之间的连接权重来优化预测结果，这一过程涉及前向传播、损失计算、反向传播和参数更新。

神经网络的类型包括前馈神经网络、卷积神经网络（CNN）、循环神经网络（RNN）和长短期记忆网络（LSTM），它们在图像识别、语音处理、自然语言处理等多个领域都有广泛应用。

PyTorch 提供了一个非常方便的接口来构建神经网络模型，即 torch.nn.Module。

我们可以继承 nn.Module 类并定义自己的网络层。

创建一个简单的神经网络：

In [36]:
import torch.nn as nn
import torch.optim as optim

In [38]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2,2)
        self.fc2 = nn.Linear(2,1)
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = SimpleNN()
print(model)


SimpleNN(
  (fc1): Linear(in_features=2, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)


训练过程：

1.前向传播（Forward Propagation）： 在前向传播阶段，输入数据通过网络层传递，每层应用权重和激活函数，直到产生输出。

2.计算损失（Calculate Loss）： 根据网络的输出和真实标签，计算损失函数的值。

3.反向传播（Backpropagation）： 反向传播利用自动求导技术计算损失函数关于每个参数的梯度。

4.参数更新（Parameter Update）： 使用优化器根据梯度更新网络的权重和偏置。

5.迭代（Iteration）： 重复上述过程，直到模型在训练数据上的性能达到满意的水平

In [45]:
# 随机输入
x = torch.randn(1,2)

# 前向传播
output = model(x)
print(output)

# 定义损失函数 （例如均方误差 MSE）
criterion = nn.MSELoss()

# 假设目标值为1
target = torch.randn(1, 1)

# 计算损失
loss = criterion(output, target)
print(loss)

tensor([[0.1776]], grad_fn=<AddmmBackward0>)
tensor(0.2018, grad_fn=<MseLossBackward0>)


In [47]:
# 定义优化器
optimizer = optim.Adam(model.parameters(), lr=0.001)

optimizer.zero_grad()
loss.backward()
optimizer.step()

训练模型是机器学习和深度学习中的核心过程，旨在通过大量数据学习模型参数，以便模型能够对新的、未见过的数据做出准确的预测。

训练模型通常包括以下几个步骤：

1.数据准备：
收集和处理数据，包括清洗、标准化和归一化。
将数据分为训练集、验证集和测试集。

2.定义模型：
选择模型架构，例如决策树、神经网络等。
初始化模型参数（权重和偏置）。

3.选择损失函数：
根据任务类型（如分类、回归）选择合适的损失函数。

4.选择优化器：
选择一个优化算法，如SGD、Adam等，来更新模型参数。

5.前向传播：
在每次迭代中，将输入数据通过模型传递，计算预测输出。

6.计算损失：
使用损失函数评估预测输出与真实标签之间的差异。

7.反向传播：
利用自动求导计算损失相对于模型参数的梯度。

8.参数更新：
根据计算出的梯度和优化器的策略更新模型参数。

9.迭代优化：
重复步骤5-8，直到模型在验证集上的性能不再提升或达到预定的迭代次数。

10.评估和测试：
使用测试集评估模型的最终性能，确保模型没有过拟合。

11.模型调优：
根据模型在测试集上的表现进行调参，如改变学习率、增加正则化等。


12.部署模型：
将训练好的模型部署到生产环境中，用于实际的预测任务。

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim

# 1.定义一个简单的神经网络
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2,2)
        self.fc2 = nn.Linear(2,1)
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 2.创建模型实例
model = SimpleNN()

#3 定义损失函数和优化器
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

#4. 假设我们有训练数据 x 和 y
X  = torch.randn(10, 2)
Y = torch.randn(10, 1)

#5. 训练循环
for epoch in range(100):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, Y)
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.8937
Epoch [20/100], Loss: 0.8722
Epoch [30/100], Loss: 0.8510
Epoch [40/100], Loss: 0.8301
Epoch [50/100], Loss: 0.8097
Epoch [60/100], Loss: 0.7900
Epoch [70/100], Loss: 0.7708
Epoch [80/100], Loss: 0.7525
Epoch [90/100], Loss: 0.7349
Epoch [100/100], Loss: 0.7182
